site_name: Stochastic Process Exercises and Solutions
theme:
  name: material
  language: zh
  features:
    - navigation.tabs # 开启顶部导航栏
    - navigation.indexes # 允许点击文件夹名称进入对应汇总页

nav:
  - 首页: index.md
  - 习题与解答:
      - 第一章: exercises/chapter_01.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.snippets # 允许跨文件嵌入内容

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
